### ISSUE TITLE
عدم اجرا در سیستم عامل با معماری arm64

### ISSUE THREAD

**Issue by rafatidev** [radkesvat/FakeTlsTunnel#24]
سلام
وقت شما بخیر
وقتی از سرور های دارای معماری arm64 استفاده میکنیم بعد از اجرا دستور خطای زیر رو میده 
-bash: ./FTT: cannot execute binary file: Exec format error

ممنون میشم برای این معماری هم در نظر بگیرید.

**Comment by radkesvat** [comment]
سلام بله ؛ اگه سرورشو پیدا کنم حتما کامپایل میزنم میزارم خروجیشو ولی اگه خواستین خودتون هم میتونین بیلد کنید مراحلش رو خیلی ساده میگم اگه موفق شدین که خوب اگه نشدین هم مشکلی نیست میزارم

اول کامپایلر رو نصب میکنید با choosennim 
> curl https://nim-lang.org/choosenim/init.sh -sSf | sh

اخر نصبش بهتون میگه یه کاری رو انجام بدین که طبق چیزی که گفته انجام بدین

بعد پروژه رو کلون کنید و با این ۲ تا دستور بیلد کنید
> nim install

> nim build

خروجی داخل پوشه dist خواهد بود

**Comment by rafatidev** [comment]
الان همینو زدم این خطا رو برگردوند :

choosenim-init: Error: Sorry, your platform (linux_arm64) is not supported by choosenim.
choosenim-init: Error: You will need to install Nim using an alternative method.
choosenim-init: Error: See the following link for more info: https://nim-lang.org/install.html

اگر راه ارتباطی مثل ایمیلی چیزی واسم بفرستید من یه سرور خام arm64 واستون بفرستم برای تست و پیاده سازی

**Comment by radkesvat** [comment]
radkesvat@telegmail.com

**Comment by rafatidev** [comment]
ارسال شد.

**Comment by radkesvat** [comment]
دریافت شد ؛ خروجی رو گرفتم بهتون میگم

**Comment by radkesvat** [comment]
نسخه arm اضافه شد از بخش release میتونید دانلود کنید 
منتهی بیلد کردنش یکمی زمان بره برای نسخه های بعدی باید یه هتزنر ۶۴ بسازم و بیلد بگیرم خودم که سرور اش پاک نشه

**Comment by rafatidev** [comment]
تست گرفتم اوکی شد
سپاسگزارم
