### ISSUE TITLE
Error GLIBC_2.27 on CentoOS 7.9

### ISSUE THREAD

**Issue by NabiKAZ** [radkesvat/FakeTlsTunnel#31]
OS:
CentOS Linux release 7.9.2009 (Core)

ldd --version
ldd (GNU libc) 2.17

Error:
./FTT: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ./FTT)

**Comment by radkesvat** [comment]
سلام

نسخه قدیمی centos استفاده میکنید؟ ترجیها نسخه جدیدترشو نصب کنید و یا ابونتو ۱۸+ و یا اگر امکانش رو ندارید باید برنامه رو همونجا کامپایل کنیم

کامپایلش کار ساده ایه طبق چیزی که میگم اجرا کنید تا خروجی تولید بشه

**Comment by radkesvat** [comment]
اول کامپایلر رو نصب میکنید با choosennim

sudo apt install build-essential
curl https://nim-lang.org/choosenim/init.sh -sSf | sh
اخر نصبش بهتون میگه یه کاری رو انجام بدین که طبق چیزی که گفته انجام بدین

بعد پروژه رو کلون کنید و با این ۲ تا دستور بیلد کنید

nim install
nim build
خروجی داخل پوشه dist خواهد بود

**Comment by NabiKAZ** [comment]
ممنون از راهنماییتون. نصب شد.

تست کردم ولی خیلی کیفیت متفاوتی نسبت به روشهای دیگه مثه iptables یا socat نگرفتم. باز ریورس ssh برای من کمی بهتره.

به هر حال ممنون.

**Comment by radkesvat** [comment]
بسیار عالی ؛ به محض اینکه از کارکرد این پروژه در لانگ ران مطمعن بشم تونل معکوس هم اوکی میکنم که به نظرم نصبت به reverse ssh, or reverse ws
مزایایی داشته باشه از جمله اینکه با پابلیک کی رمز نکنه تا cpu usage زیاد نباشه و غیره
