### ISSUE TITLE
مشکل اجرا nohub

### ISSUE THREAD

**Issue by SahandSOne** [radkesvat/FakeTlsTunnel#32]
با سلام و خسته نباشید
من روی اوبونتو 22 اجرا کردم و این ارور رو میده. لطفا راهنمایی کنید
![Screenshot from 2023-06-20 21-16-03](https://github.com/radkesvat/FakeTlsTunnel/assets/134105392/4178e35b-65c0-4e8e-bcb8-0fd96a125003)

**Comment by radkesvat** [comment]
این دستورو اجرا کنید احتمالا مشکلتون رفع بشه
> dpkg -S /usr/bin/nohup

**Comment by SahandSOne** [comment]
اجرا کردم قبلا. نشد 
ممنون میشم اگه راحلی برای این مسله بود. بفرمایید تا همه استفاده بکنن

**Comment by radkesvat** [comment]
الان nohup رو نصب کردین درسته؟ پس میتونید اجرا کنید

**Comment by SahandSOne** [comment]
> الان nohup رو نصب کردین درسته؟ پس میتونید اجرا کنید


بله نصب هست. این دستور شما رو هم اجرا کردم

![Screenshot from 2023-06-20 22-02-40](https://github.com/radkesvat/FakeTlsTunnel/assets/134105392/380856f5-3411-4763-a40f-aae7211cbd38)

**Comment by SahandSOne** [comment]
مثل اینکه به جای nohub باید از nohup استفاده بشه :(((

**Comment by radkesvat** [comment]
درسته داخل مثالی هم که زدم داخل توضیحات nohup نوشته شده بود نه nohub

**Comment by SahandSOne** [comment]
> درسته داخل مثالی هم که زدم داخل توضیحات nohup نوشته شده بود نه nohub


دقیقا. خیلی معذرت خواهی میکنم 
دمتون گرم

**Comment by radkesvat** [comment]
خواهش میکنم پیش میاد
