### ISSUE TITLE
مشکل قطع شدن کانکشن به محض باز شدن

### ISSUE THREAD

**Issue by PillarsDev** [radkesvat/FakeTlsTunnel#37]
سلام
مشکلی که من دارم اینه که روی سرورم به محض اینکه یه تونل ایجاد میشه همون لحظه میزنه Closed Remote و کانکشن قطع میشه
مشکل sni یا پورت هم نیس چون روی یه سرور دیگه که تست میکنم با همین مشخصات درست کار میکنه ولی روی این سرورم مشکل داره
سرور آی پی ۶ داشت که غیرفعالش کردم ولی بازم مشکل حل نشد
ممنون میشم اگه چیزی به ذهنت میرسه راهنماییم کنی؟
![Screenshot 2023-06-23 at 12 04 46 PM](https://github.com/radkesvat/FakeTlsTunnel/assets/137491493/4421900b-e382-48bd-b6c0-043ac7593a2d)

**Comment by radkesvat** [comment]
close remote 

اگه در لحظه بیاد یعنی فایروال شخصا جولوی اتصالو میگیره ؛ معمولا با تغییر sni درست میشه ؛ این sni هارو تست کنید و نتیجه رو بگین

> alexa.com

> superuser.com

**Comment by radkesvat** [comment]
البته این لاگ از سرور خارج هست و این طبیعیه من مشکلی نمیبینم اینجا
