### ISSUE TITLE
زمان اجرا کد روی سرور خارج ارور memoryمیده 

### ISSUE THREAD

**Issue by SasanKHZN** [radkesvat/FakeTlsTunnel#71]
Firewall stopped and disabled on system startup
fs.file-max = 100000
[GC] total memory: 528384
[GC] occupied memory: 23808

Mode Server:   0.0.0.0 <-> (xxxxxxxx with ip 1.1.1.1)
Started tcp server... 0.0.0.0:443
[GC] total memory: 528384
[GC] occupied memory: 96080

[GC] total memory: 528384
[GC] occupied memory: 96080

[GC] total memory: 528384
[GC] occupied memory: 96080
روی هر سروری باشه همین ارورو میده

**Comment by radkesvat** [comment]
این ارور نیست لاگ هستش

**Comment by RezaKardoost** [comment]
امکانش هست لاگ رو غیر فعال کنیم یا اینکه سطع لاگ (Log level) رو بتونیم خودمون تعیین کنیم؟ مثلا فقط ارور ها رو لاگ کنه.
اخه در حالت سرویس، حجم log های FTT در مسیر var/log/journal به مرور زمان رشد بالایی داره و مجبورم مدام دستی حذف کنم.

**Comment by radkesvat** [comment]
برای غیر فعال کردن لاگ اخر دستور این عبارت رو بنویسید

> 2>&1 >/dev/null

**Comment by milad73n** [comment]
جناب راد این کامند رو بار اول زدم درست شد ولی بعد چند ساعت دوباره مموری ارور میده و این کامند رو هر چند بار میزنم تاثیری نداره
۴ ماهی بود بدون مشکل کار میکرد الان یهویی اینطوری شده

**Comment by radkesvat** [comment]
sni تغییر بدین و تست کنین

**Comment by milad73n** [comment]
الان چه sni بزنم بهتره؟

**Comment by radkesvat** [comment]
ببینید بستگی داره یه چند تا تست کنید خوبشو پیدا میکنید
